# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "MyDriver"
include-before = [
	"cmake/msvc-configurations.cmake",
]

[variables]
CMAKE_MODULE_PATH = "${CMAKE_CURRENT_SOURCE_DIR}/cmake"

[find-package.WDK]

[template.driver]
type = "executable"
add-function = "wdk_add_driver"
compile-features = ["cxx_std_17"]

[target.MyDriver]
type = "driver"
sources = [
    "src/MyDriver/*.cpp",
    "src/MyDriver/*.hpp",
]